### ISSUE TITLE
Compiler warnings.

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/nimgame2#1]
Installing with Nimble gives some compilation warnings.

See below:

<pre>
$ nim -v

Nim Compiler Version 0.16.0 (2017-01-08) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 5947403e84ba44397b35f93f9d327c76e794210f
active boot switches: -d:release

$ trash ~/.nimble/

$ nimble update

Downloading Official package list
    Success Package list downloaded.

$ nimble install nimgame2

Downloading Official package list
    Success Package list downloaded.
david@david:/tmp$ nimble install nimgame2
Downloading https://github.com/Vladar4/nimgame2 using git
   Warning: File 'mainscene.nim' inside package 'nimgame2' is outside of the permitted namespace, should be inside a directory named 'nimgame2' but is in a directory named 'demos/demo4' instead. This will be an error in the future.
      Hint: Rename the directory to 'nimgame2' or prevent its installation by adding `skipDirs = @["demos/demo4"]` to the .nimble file.
  Verifying dependencies for nimgame2@0.1.0
 Installing sdl2_nim@any version
Downloading https://github.com/Vladar4/sdl2_nim using git
   Warning: File 'sdl_gfx_primitives.nim' inside package 'sdl2_nim' is outside of the permitted namespace, should be inside a directory named 'sdl2_nim' but is in a directory named 'sdl2' instead. This will be an error in the future.
      Hint: Rename the directory to 'sdl2_nim' or prevent its installation by adding `skipDirs = @["sdl2"]` to the .nimble file.
  Verifying dependencies for sdl2_nim@0.96
 Installing sdl2_nim@0.96
   Success: sdl2_nim installed successfully.
 Installing nimgame2@0.1.0
   Success: nimgame2 installed successfully.

<pre>

**Comment by Vladar4** [comment]
As the engine is still in alpha, please use the latest version of nimgame2 by installing it with

`nimble install nimgame2@#head`

**Comment by wizzardx** [comment]
Thanks. Tried that but got a new error:

<pre>
$ trash ~/.nimble

$ nimble update

$ nimble install nimble install nimgame2@#head

Downloading https://github.com/nim-lang/nimble using git
  Verifying dependencies for nimble@0.8.2
 Installing compiler@#head
Downloading https://github.com/nim-lang/Nim.git using git
  Verifying dependencies for compiler@#head
 Installing compiler@#head
   Success: compiler installed successfully.
 Installing nimble@0.8.2
   Building nimble/nimble using c backend
   Warning: Binary 'nimble' was already installed from source directory. Will be overwritten.
Traceback (most recent call last)
nimble.nim(1073)         nimble
nimble.nim(999)          doAction
nimble.nim(608)          install
nimble.nim(466)          installFromDir
tools.nim(87)            copyFileD
os.nim(1290)             copyFileWithPermissions
os.nim(599)              copyFile
os.nim(153)              raiseOSError
Error: unhandled exception: No such file or directory [OSError]

</pre>

Any advice?

**Comment by Vladar4** [comment]
Here's your error:
`nimble install nimble install nimgame2@#head`
Should be
`nimble install nimgame2@#head`

**Comment by wizzardx** [comment]
Thanks, that fixes the nimgame2 warning. Also fixes my one other ticket.
