### ISSUE TITLE
Bad error checking for mixer init

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/nimgame2#12]
Hi there.

According to sdl_mixer.nim:
```
  # Init SDL_mixer
  if mix.init(mixerFlags) == 0:
    sdl.logCritical(
      sdl.LogCategoryError, "Can't initialize SDL_mixer: %s", mix.getError())
    return false
```

Where getError refers to SDL_GetError

But according to the SDL spec:

https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_frame.html

We're meant to be using the Mix_GetError function.

**Comment by Vladar4** [comment]
```mix.getError()``` refers to sdl2/sdl_mixer's [getError()](https://vladar4.github.io/sdl2_nim/sdl_mixer.html#getError.t,) (which is just a binding to ```SDL_GetError()``` in the [original code](https://hg.libsdl.org/SDL_mixer/file/929c90225030/SDL_mixer.h#l638) at the moment anyway).
