### ISSUE TITLE
Update required version of SDL_Image to 2.0.2

### ISSUE THREAD

**Issue by PMunch** [Vladar4/nimgame2#15]
Tried to compile and run the demo1 files but I got the runtime error `could not import: IMG_isSVG` which is from SDL_Image. SVG features were added in SDL_Image 2.0.2, but the README lists 2.0.1 as the required version.

**Comment by PMunch** [comment]
Another possibility is to add the deadCodeElim pragma to the SDL wrapper so that unused calls will get removed and therefore not try to load the new SVG functions.

**Comment by Vladar4** [comment]
Yep, I thin it should help. The whole problem is that there's still no SDL2_image 2.0.2 in the repos (at least in Arch) more than a month after release.

https://github.com/Vladar4/sdl2_nim/commit/cbf59deeaf8cf5c41ce67ef294e1fbadb1ddb1b5 should help (if you are using nimble, don't forget to install it with ```nimble install sdl2_nim@#head```).

Please tell if it fixed your problem.

**Comment by PMunch** [comment]
Yeah that seemed to work. Strange that Arch hasn't updated their SDL_Image package yet..
