### ISSUE TITLE
Broken "view source" links in documentation

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/nimgame2#16]
eg, if I go over to this page:

https://vladar4.github.io/nimgame2/docs/draw.html

And then click "view source" for the "pixel" function.

That takes me here:

https://vladar4.github.io/tree/master/draw.nim#L36

Where github reports a "404" error, "There isn't a GitHub Pages site here."

**Comment by Vladar4** [comment]
Will look into it as the new Nim version will be released.

**Comment by Vladar4** [comment]
Fixed in v0.6.
