### ISSUE TITLE
Type mismatch on joystick procs in input.nim

### ISSUE THREAD

**Issue by zetashift** [Vladar4/nimgame2#17]
On windows10 x64 having a problem which can be temporarily solved by commenting out the access to the sequence. It stops the compilation process but I didn't need joystick support!
 
This is where the first error starts: 

https://github.com/Vladar4/nimgame2/blob/67fe6fb7b258d1a624e193a71f11754cca3752bb/nimgame2/input.nim#L403-L414

2 others(same error message) occured on line: 507 and 530
This is the error message:
`C:\Users\rskar\.nimble\pkgs\nimgame2-#head\nimgame2\input.nim(507, 21) Error: type mismatch: got (array[0..254, int], int)
but expected one of:
proc `[]`[I: Ordinal; T](a: T; i: I): T
proc `[]`[T](s: openArray[T]; i: BackwardsIndex): T
proc `[]`[T, U](s: string; x: HSlice[T, U]): string
proc `[]`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex): var T
proc `[]`[Idx, T, U, V](a: array[Idx, T]; x: HSlice[U, V]): seq[T]
proc `[]`[Idx, T](a: array[Idx, T]; i: BackwardsIndex): T
proc `[]`[T](s: var openArray[T]; i: BackwardsIndex): var T
proc `[]`[T, U, V](s: openArray[T]; x: HSlice[U, V]): seq[T]
proc `[]`(s: string; i: BackwardsIndex): char
template `[]`[Idx; T](a: array[Idx, T]; x: Scancode): T

expression: [](j.pressed, button)`

**Comment by Vladar4** [comment]
A couple of questions:

1. What Nim version are you using?

2. What Nimgame2 version are you compiling (master or devel branch)?

**Comment by zetashift** [comment]
Yeah sorry about not mentioning this:
1. Nim version 0.17.3
2. nimgame2 version 0.5.0 according to nimgame2.nimble (used nimble install nimgame2@#head to install this)

**Comment by Vladar4** [comment]
Well, that's where your problem lies apparently. Due to the syntax changes in the newer Nim versions, you have two options right now:
1. Use Nim v0.17.0 with Nimgame2 v0.5
2. Use Nim v0.17.3 with the [devel](https://github.com/Vladar4/nimgame2/tree/devel) branch of the Nimgame2.

Please try one of these and tell me if it helps.

Devel branch will become v0.6 in the future (but not before the next Nim release for sure).

**Comment by zetashift** [comment]
I chose for the second option and it's working! Thank you for enhancing my journey into learning gamedev!

**Comment by Vladar4** [comment]
Glad it helped! Closing this issue then. Feel free to report any found bugs and issues and don't forget to check out [tutorials](https://vladar4.github.io/nimgame2/tutorials.html) and [snippets](https://vladar4.github.io/nimgame2/snippets.html) if you haven't already.
