### ISSUE TITLE
Should we include a zip with all of the dynamic libraries?

### ISSUE THREAD

**Issue by CodeDoes** [Vladar4/nimgame2#18]
I had to spend a long time downloading all the DLL files. Perhaps we could make it easier?
I coppied some of the dlls from ggroto game.
Maybe one zip containing all supported DLLs?

**Comment by Vladar4** [comment]
The binary releases are intended as "unpack-and-run" (or just "download-and-run" for Linux AppImages). Plus, DLLs will change over time (they already did), creating confusion. I'd rather provide a "no-DLL" archive alongside the full one.
