### ISSUE TITLE
Unable to compile demos if library installed with "nimble install nimgame2" 

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/nimgame2#2]
Get a compile error if we first install nimgame2 with nimble, and then do a git clone and attempt to run examples.

<pre>

$ nimble update

$ nimble install nimgame2

$ git clone https://github.com/Vladar4/nimgame2

$ cd nimgame2/demos/demo1

$ nim c -r demo1
...
demo1.nim(2, 11) Error: cannot open 'nimgame2/nimgame'

</pre>

This succeeds, however:

<pre>

$ trash ~/.nimble

$ nimble update

$ git clone https://github.com/Vladar4/nimgame2

$ cd nimgame2

$ nimble install

$ cd demos/demo1

$ nim -c demo1.nim

</pre>

**Comment by Vladar4** [comment]
See https://github.com/Vladar4/nimgame2/issues/1

**Comment by wizzardx** [comment]
Thanks, that works for me.
