### ISSUE TITLE
What is the mosaic module? 

### ISSUE THREAD

**Issue by CodeDoes** [Vladar4/nimgame2#20]
is it some sort of tile map?

**Comment by Vladar4** [comment]
[Mosaic](https://vladar4.github.io/nimgame2/docs/mosaic.html) is mostly used for generating GUI elements' textures of different sizes from the "skin" files.

See usage examples:

* https://vladar4.github.io/nimgame2/snippets.html#gui_text_input
* https://vladar4.github.io/nimgame2/tut102_platformer.html#assets
* https://github.com/Vladar4/ng2gggrotto/blob/master/src/menubutton.nim#L29
