### ISSUE TITLE
Bounce game not compiling

### ISSUE THREAD

**Issue by Skaruts** [Vladar4/nimgame2#23]
Hey there, I was just now following the tutorial for the Bounce game, and right at the starting fase (when it should compile and run as a blank window), it gives me this error:

```
C:\Users\...\.nimble\pkgs\nimgame2-0.5.0\nimgame2\input.nim(413, 18) Error: type mismatch: got <array[0..254, int], int, int literal(0)>
but expected one of: 
proc `[]=`[T, U](s: var string; x: HSlice[T, U]; b: string)
proc `[]=`[I: Ordinal; T, S](a: T; i: I; x: S)
proc `[]=`[Idx, T, U, V](a: var array[Idx, T]; x: HSlice[U, V]; b: openArray[T])
proc `[]=`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex; x: T)
proc `[]=`(s: var string; i: BackwardsIndex; x: char)
proc `[]=`[T](s: var openArray[T]; i: BackwardsIndex; x: T)
proc `[]=`[T, U, V](s: var seq[T]; x: HSlice[U, V]; b: openArray[T])

expression: []=(j.pressed, i, 0)
```
I copied and pasted the code from the site, just to be sure, and it still gives me the same error. I also downloaded the entire source for the game and it didn't compile due to this same issue.

I'm can't be sure if this is something wrong with nimgame2 or with my own installation, as I'm not too good with these things. But I was thinking it might be related to ng2 not having yet caught on to Nim 0.18.

**Comment by CodeDoes** [comment]
Add backticks? `[]=`(j.pressed, i, 0)

**Comment by Vladar4** [comment]
Use [devel branch](https://github.com/Vladar4/nimgame2/tree/devel) and tell me if it helps.

**Comment by Skaruts** [comment]
I suppose to install it it's with `nimble install nimgame2@#devel`? (I uninstalled the previous one)

Still gives me an error, but a different one now.

```
C:\Users\...\.nimble\pkgs\nimgame2-0.5.0\nimgame2\input.nim(413, 18) Error: type mismatch: got <array[0..254, int], int, int literal(0)>
but expected one of: 
proc `[]=`[T, U](s: var string; x: HSlice[T, U]; b: string)
proc `[]=`[I: Ordinal; T, S](a: T; i: I; x: S)
proc `[]=`[Idx, T, U, V](a: var array[Idx, T]; x: HSlice[U, V]; b: openArray[T])
proc `[]=`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex; x: T)
proc `[]=`(s: var string; i: BackwardsIndex; x: char)
proc `[]=`[T](s: var openArray[T]; i: BackwardsIndex; x: T)
proc `[]=`[T, U, V](s: var seq[T]; x: HSlice[U, V]; b: openArray[T])

expression: []=(j.pressed, i, 0)
```

**Comment by Vladar4** [comment]
It look like you still link to the stable version (from ```C:\Users\...\.nimble\pkgs\nimgame2-0.5.0\``` path and line number). 

Please check if you really use the devel branch here (nimble path should be ```nimble\pkgs\nimgame2-#devel```).

**Comment by Skaruts** [comment]
First time I installed it I didn't uninstall the previous one, and I saw the path was nimble\pkgs\nimgame2-#head. So I though it was still using the master branch, and I uninstalled both, and installed only the devel one, and "nimgame2-0.5.0" was the path that it used then. 

I suppose it can only be using the devel branch because I don't have the master installed.

**Comment by Skaruts** [comment]
Actually it seems to be working now. I uninstalled/installed it again, to double check, and now it compiled (with the devel branch). It's only complaining that I didn't give it SDL_Image.dll. However, SDL2 doesn't seem to be shipped with those files...

**Comment by Vladar4** [comment]
> However, SDL2 doesn't seem to be shipped with those files...

Of course. See here: https://www.libsdl.org/projects/ (except for the [sdl2_gfx](http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/)).

**Comment by Skaruts** [comment]
I wonder why they don't have all that on the downloads page... They used to with sdl 1.2, as far as I remember.

Anyway, sdl2_gfx doesn't seem to come compiled, and that's kind of a roadblock for me.

**Comment by Vladar4** [comment]
Compiling sdl2_gfx isn't that hard. Anyway, I've added links to the binaries into the [sdl2_nim](https://github.com/Vladar4/sdl2_nim/blob/master/LINKS.md) repo.

**Comment by irskep** [comment]
Any plans to merge the changes and do a release so we don't have to use a shady development branch to use this library? :-)

**Comment by Vladar4** [comment]
Fair enough! I should have done this long time ago.

https://github.com/Vladar4/nimgame2/releases/tag/v0.6
