### ISSUE TITLE
input.nim error when compiling any demo

### ISSUE THREAD

**Issue by matkuki** [Vladar4/nimgame2#26]
Hi,

This error appears when trying to compile any of the demos:
```
...\.nimble\pkgs\nimgame2-#devel\nimgame2\input.nim(403, 16) Error: type mismatch: got <seq[Joystick], nil>
but expected one of:
proc `==`[T](x, y: seq[T]): bool
  first type mismatch at position: 2
  required type: seq[T]
  but expression 'nil' is of type: nil

expression: joysticks == nil
```
Seems like a error introduced by a newer Nim version. I'm using Nim 0.18.1 that was compiled today.

**Comment by Vladar4** [comment]
It seems your assumption is correct. Let me know if 49703af32a4db1fa286e5f511695ec5c23cdb09c fixed the issue.

**Comment by matkuki** [comment]
@Vladar4 
Great, that did it! Thanks.
