### ISSUE TITLE
GuiWidget actions doesn't respond to mouse clicks

### ISSUE THREAD

**Issue by kidandcat** [Vladar4/nimgame2#33]
GuiWidget doesn't respond to mouse clicks.

I've done the Platformer tutorial. It works perfectly but the actions assigned to Menu buttons aren't being called.

Nim Compiler Version 0.20.2 [Windows: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release

**Comment by Vladar4** [comment]
Just tested with the Nim v1.0 and it seems to be working.
Need to see your code here.

**Comment by kidandcat** [comment]
https://github.com/kidandcat/platformer


PD: awesome job the tutorials and the library, thank you so much!

**Comment by Vladar4** [comment]
I've compiled your source with Nim v1.0 and menu buttons work fine as well.

Could you try updating your compiler to 1.0 and see if it helps?

P.S.: Just got another idea: do you use `--multimethods:on` key when compiling? It is a requirement with the new compiler versions.

**Comment by kidandcat** [comment]
The switch multimethods was the key, thanks!

**Comment by Vladar4** [comment]
I've added the note in the master branch readme for clarity: 980a7c2433b3581011d2b6c9f02bdd05830fb88b
