### ISSUE TITLE
Compile error in devel branch

### ISSUE THREAD

**Issue by Jjp137** [Vladar4/nimgame2#38]
This short example:

```nim
import nimgame2/texturegraphic
```

...fails to compile with this error message:
```
/home/jjp/.nimble/pkgs/nimgame2-#devel/nimgame2/utils.nim(193, 14) template/generic instantiation of `bytesPerPixel` from here
/home/jjp/.nimble/pkgs/sdl2_nim-#head/sdl2/private/pixels.nim(137, 18) Error: type mismatch: got <uint32> but expected 'int literal(2)'
```

Occurs on Nim 1.0.4 as well as the devel compiler. I don't really understand the error...

**Comment by Vladar4** [comment]
Please check if this fixes the issue (just update sdl2_nim@#head though nimble)
https://github.com/Vladar4/sdl2_nim/commit/90336b89649206c039dc9c8402385f70cef6f14c

**Comment by Jjp137** [comment]
That does fix the issue; thanks!
