### ISSUE TITLE
How does ng2 handles sprite batching?

### ISSUE THREAD

**Issue by rishavs** [Vladar4/nimgame2#39]
Sprite batching and camera occlusion are probably the 2 most important performance aspects of 2d games IMO. How does ng2 handles batching? 
Is the batching done automatically ?

**Comment by Vladar4** [comment]
AFAIK, SDL2 does not have any procedures to do it manually, though some driver-depended action might be going under the hood.

**Comment by rishavs** [comment]
Thanks.
I searched a bit more on this and this comment in the sdl discourse was pretty informative; https://discourse.libsdl.org/t/confused-about-necessity-of-batch-rendering/24048/7

So apparently, SDL has no batching builtin even though that can be added on top of it.
Also, there is a layer called sdl_gpu which addresses some of these shortcomings https://github.com/grimfang4/sdl-gpu

**Comment by rishavs** [comment]
More stalking yielded 
https://twitter.com/icculus/status/1042081368216350723?lang=en

and the supposed commit for batching in SDL is https://hg.libsdl.org/SDL/rev/0d5da1145cad
