### ISSUE TITLE
nim CI failure: nimgame2\utils.nim(169, 31) Error: type mismatch: got <ptr RWops, ptr char, csize, int literal(1000)>

### ISSUE THREAD

**Issue by timotheecour** [Vladar4/nimgame2#40]
see https://github.com/nim-lang/Nim/pull/13550#issuecomment-598648034

EDIT: see PR #41 that fixes it

**Comment by Vladar4** [comment]
I believe it's already fixed in devel: https://github.com/Vladar4/nimgame2/commit/8ea89ba773de27db2c8f7a9c277a0ad5f9da09d4#diff-cdb07207a519ef4c7003f883c113dc5bL241
Please, confirm.

**Comment by timotheecour** [comment]
devel doesn't help; nim CI clones the main branch (which is set to master in your repo)
so either important_packages.nim needs to be updated, or your repo's master needs to be updated; 
WDYT?


Note: IMO it's possible to have nim CI test both your devel AND master branch; but support for that feature in important_packages may need to be added for that to work

**Comment by Vladar4** [comment]
Fair enough.
I've applied this commit into the master branch: 4f36797aa85e171c17dc8babcb236be577569693
Please, let me know if it solves the issue.

**Comment by timotheecour** [comment]
should be but haven't verified, closing for now, thanks!
