### ISSUE TITLE
Demo compilation error

### ISSUE THREAD

**Issue by matkuki** [Vladar4/nimgame2#47]
Hi,

Specs:
- Windows 10 x64
- Nim: Devel -> `Nim Compiler Version 1.5.1 [Windows: amd64]`

Compiling any demo gives:
```bash
.../.nimble\pkgs\nimgame2-0.6.1\nimgame2\utils.nim(169, 27) Error: type mismatch: got <ptr RWops, ptr char, int, int literal(1000)>
but expected one of:
proc rwRead(context: ptr RWops; p: pointer; size: csize_t; maxnum: csize_t): csize_t
  first type mismatch at position: 3
  required type for size: csize_t
  but expression '1' is of type: int

expression: rwRead(src, addr(result[r]), 1, 1000)
```

**Comment by matkuki** [comment]
@Vladar4 
I added conversions where there were type mismatches and got it to compile, but there are quite a lot of them.
Not sure that that won't mess anything up in the codebase.

**Comment by Vladar4** [comment]
Have you tried using devel version?

Alternatively, you could apply this patch from the devel: 4f36797aa85e171c17dc8babcb236be577569693

**Comment by matkuki** [comment]
@Vladar4 
Thanks, devel works.
