### ISSUE TITLE
Nimsuggest does not work

### ISSUE THREAD

**Issue by vanyle** [Vladar4/nimgame2#48]
When importing the nimgame2 functions, nimsuggest does not work.
I go it to work by changing the following:

Inside the `.nimble` file, I added a name field:
```nim
# Package
name = "nimgame2"
version = "0.6.2"
author = "Vladar"
description = "A simple 2D game engine for Nim language."
license = "MIT"
```

Inside the root directory, I created a `nimgame2` file that exports all the symbols of the library so that only one import is needed to use the library:
```nim
import
    nimgame2/nimgame,
    nimgame2/draw,
    nimgame2/entity,
    nimgame2/settings,
    nimgame2/scene,
    nimgame2/utils,
    nimgame2/graphic,
    nimgame2/texturegraphic,
    nimgame2/types,
    nimgame2/input

export nimgame,draw,entity,settings,scene,utils,graphic,texturegraphic,types,input
# More imports / exports are needed here ...
```

**Comment by Vladar4** [comment]
Sure, I'll accept such pull request.

**Comment by metagn** [comment]
What is your nim/nimble version? Nimble breaks if you define `name` (https://github.com/nim-lang/nimble/issues/237), but if you have a very old version it might require it.

**Comment by vanyle** [comment]
`nimble v0.13.1 compiled at 2021-11-04 21:52:10`

```
Nim Compiler Version 1.6.0 [Windows: amd64]
Compiled at 2021-11-04
Copyright (c) 2006-2021 by Andreas Rumpf
```

I'm not 100% sure what causes the nimsuggest issue. It might be the name part or the import part.

**Comment by Vladar4** [comment]
The [documentation](https://github.com/nim-lang/nimble#nimble-reference) says that
```name - The name of the package. (This is not required in the new NimScript format)```

Could you check if nimsuggest works with the current setup (without the name entry)?

**Comment by vanyle** [comment]
Yup, now it does !
