### ISSUE TITLE
Error with 'sdl.HatPosition' while compiling demos

### ISSUE THREAD

**Issue by zetashift** [Vladar4/nimgame2#7]
On Windows 10 64-bit, got all the SDL runtime libs and nimgame2 0.4.0.

Getting the following error while running any of the demos during compilation.
`PS C:\Users\rskar\stack\dev\gamedev\nimgame2-master\demos\demo1> nim c -r .\demo1.nim
Hint: used config file 'C:\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: demo1 [Processing]
Hint: nimgame [Processing]
Hint: math [Processing]
Hint: parseutils [Processing]
Hint: random [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: algorithm [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: sdl [Processing]
Hint: sdl_image [Processing]
Hint: sdl_ttf [Processing]
Hint: sdl_mixer [Processing]
Hint: audio [Processing]
Hint: types [Processing]
Hint: settings [Processing]
Hint: utils [Processing]
Hint: parsecsv [Processing]
Hint: lexbase [Processing]
Hint: streams [Processing]
Hint: texturegraphic [Processing]
Hint: graphic [Processing]
Hint: indexedimage [Processing]
Hint: count [Processing]
Hint: draw [Processing]
Hint: sdl_gfx_primitives [Processing]
Hint: sdl_gfx_primitives_font [Processing]
Hint: input [Processing]
C:\Users\rskar\.nimble\pkgs\nimgame2-0.4.0\nimgame2\input.nim(315, 24) Error: cannot export: sdl.HatPosition`

**Comment by Vladar4** [comment]
You should update your sdl2_nim package with `nimble install sdl2_nim@#head` as required by the nimgame2.nimble file.

Please, report if this fixes your problem.

**Comment by zetashift** [comment]
Indeed it does, thanks!

**Comment by Vladar4** [comment]
You are welcome! I plan to release a new sdl2_nim version along with the next nimgame2 release to aid such issues in the future.
