### ISSUE TITLE
Compile options

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/nimgame2#8]
Hi there!

I see a recommendation for this kind of compilation command-line:

-d:release --opt:speed

But doesn't -d:release automatically mean --opt:speed? The speed option seems redundant.

**Comment by Vladar4** [comment]
Do you have an actual source for that? Compiler User Guide does not suggest such behavior and there's also --opt:none and --opt:size modes.

**Comment by wizzardx** [comment]
I think I've seen it in a few random places (eg, generated build scripts, or misc guides and tutorials).

But probably the most canonical location for how options work, eg on a per-compiler level, is over in here in the Nim lang git source code:

config/nim.cfg

There's this section in there, that says to use the speed option if you're compiling for release mode:

```
@if release:
  opt:speed
@end
```

So I think having an explicit '--speed' option is mainly useful for a customized version of nim.cfg where release mode doesn't include the speed option.

**Comment by Vladar4** [comment]
Thanks. Though I think it is better to leave the option there both for the explicitness and for rare cases of different nim.cfg. Anyway, it is just a recommendation.

**Comment by wizzardx** [comment]
Fair enough :-).
I'll close this ticket.
