### ISSUE TITLE
Composing TextGraphic

### ISSUE THREAD

**Issue by floydnunez** [Vladar4/nimgame2#9]
I am trying to compose two TextGraphics, so I can create text that has a shadow, which makes for better visibility.

What can I do? I am not finding a way to do this; also, in general, how do you compose two Graphic objects?

**Comment by Vladar4** [comment]
The easiest way is to use grouping by selecting one entity as the parent of other. See [demo6](https://github.com/Vladar4/nimgame2/tree/master/demos/demo6).

More complex (and probably more efficient) way is to create new Font type (from ``BitmapFont`` or ``TrueTypeFont``) and program needed functionality in its ``render()`` procedures.

P.S.: I have changed ``renderLine()`` and ``renderText()`` to base methods of ``Font`` in [devel branch](https://github.com/Vladar4/nimgame2/blob/devel/nimgame2/font.nim) to minimize the copy-pasting when creating new Font types.

**Comment by floydnunez** [comment]
Ah cool, cool.

Thanks for answering.
